### ISSUE TITLE
Can I block websites using dnsserver.swift?

### ISSUE THREAD

**Issue by rajaunleashed** [zhuhaow/NEKit#110]
I am working on an iOS app to block website using dns server, so Can I block websites using dnsserver.swift?

**Comment by zhuhaow** [comment]
I think you should just use `NEFilterProvider`.

**Comment by Ricardo1980** [comment]
But NEFilterProvider requires supervisor/managed mode.
Can I filter websites using dnsserver.swift in a device that is not in supervisor mode? Thanks a lot.

**Comment by Ricardo1980** [comment]
It is a special mode in the iPhone you have to use to access several Network Extensions, like for example NEDNSProxyProvider
https://forums.developer.apple.com/thread/67613
(managed, supervised or supervisor mode)
Basically, you have to reset completely your phone, which is a pain in the ass, so if I can avoid it, even better.

**Comment by Ricardo1980** [comment]
@zhuhaow Thanks

I'm trying to do your last approach.

I'm trying to run a DNS server locally and point that computer to itself.

However, after calling "start", it seems no server runs. Using nmap I don't see any port was opened.
Checking the source code I see that the start method is completely empty.
How should I start the DNS server.

Thanks a lot for help.

![screen shot 2018-05-24 at 14 43 45](https://user-images.githubusercontent.com/738681/40489507-2ed45c1e-5f61-11e8-9edf-144de35ad449.png)

**Comment by zhuhaow** [comment]
`DNSServer` is a just a concept, it is not a server actually listening on a port.

**Comment by Ricardo1980** [comment]
"DNSServer is a just a concept, it is not a server actually listening on a port."

That's confusing, I thought it was an actual server. Reading the documentation I was completely sure it was a server.

**Comment by zhuhaow** [comment]
It a server in general, it just does not listen on a port, that's it. 
It handles input and generates output.

**Comment by Ricardo1980** [comment]
But, is there a way to create an actual DNS server using NEKit? 
Thanks for reply.

**Comment by zhuhaow** [comment]
What do you mean an actual DNS server? A server listening on port 53 relay data back and forth with `DNSServer`? That would probably take just several lines.

But you can't do it on iOS since you can't listen on any port less then 1024 without root permission.

**Comment by Ricardo1980** [comment]
"But you can't do it on iOS since you can't listen on any port less then 1024 without root permission."
Thanks for that.
That means I have to find another approach.

**Comment by zhuhaow** [comment]
> You just need to:
> 
> Set the system DNS to some private address, let's say A.
> Route A to tun interface.
> Parse the DNS request received, return some fake IP (better private ones) for domain you want to ban. (code in NEKit can help) If you want to speed things up, you can also route a fake IP which sends RST for all TCP packet so the connection will be reset immediately instead of waiting for timeout.
> Forward DNS request to the genuine remote server and write the response back to tun.
> Update genuine DNS server when system network configuration changes.

**Comment by Ricardo1980** [comment]
Thanks for reply.

"Does what I said make sense to you?"
Not really, I don't know about VPN tunnels or advance networking, just basic networking.
I start reading right now.
I guess when you say Network Extensions you mean this:
https://developer.apple.com/documentation/networkextension

Given that you know about networks, let me ask you if this is technically possible:
Change the current DNS configuration to point to the localhost (it works because I can test it with OpenDNS). I already did that following the same approach than "DNS Override", that is, using https://stackoverflow.com/questions/42874507/redirect-all-dns-requests-to-custom-resolver-in-ios-app
Create a local DNS server to filter a list of URLs that are stored locally by the app.
I guess I have to do something with tunnels as you told me, but I have to spend time studying that because I have no idea about that topic.

Thanks.

**Comment by zhuhaow** [comment]
You can't create a real DNS server on iOS localhost or any other addresses since you can't listen on port 53, and there is no way to specify a different DNS port. 

But with Network Extension, you can change the system DNS. So you need to give the system an illusion that there is a DNS server running at the 53 port of some address you specify. You do this by route the traffic to that address to the (u)tun interface created by Network Extension and process the request there and write response back.

Hope that clarify it.

**Comment by Ricardo1980** [comment]
Yes. Thank you very much for your help, I appreciate it a lot.
