### ISSUE TITLE
did you consider replace tun2sock with fqrouter method?

### ISSUE THREAD

**Issue by simpzan** [zhuhaow/NEKit#18]
the ip packets to bytes method used in fq router is explained here. http://fqrouter.tumblr.com/post/51474945203/socks%E4%BB%A3%E7%90%86%E8%BD%ACvpn

**Comment by zhuhaow** [comment]
Thank you for pointing that out. I tried and it was not working. See Router.swift. I'm not sure it is because there is some limitation on the TUN interface (seems like it will not forward packets to itself) or I just did something wrong.

Zhuhao Wang

2016年9月24日 +0800 23:44 Samuel <notifications@github.com>，写道：

**Comment by simpzan** [comment]
did you try to zero the checksum field? like the following code?
https://github.com/fqrouter/fqrouter/blob/master/manager/vpn.py#L94

**Comment by zhuhaow** [comment]
I do not think it is the case. If I remember right I implemented the checksum correctly. Is there any reason that setting this to zero would make a difference than setting it to the real one?

2016年9月25日 +0800 09:11 Samuel <notifications@github.com>，写道：

**Comment by simpzan** [comment]
I don't know either. I want to try it myself, but I found some classes are missing, do you have them? If so could you share?

**Comment by zhuhaow** [comment]
I think every file needed is in the repo, just need to add to the project.
Take a look at IPStack/Packet/

-------------------
Zhuhao Wang
Zhejiang university

2016年9月25日 +0800 09:22 Samuel <notifications@github.com>，写道：

**Comment by simpzan** [comment]
I tried it, it does not work on tcp server in app extension, but it works on tcp server on containing app. 

I asked the question on stackoverflow here http://stackoverflow.com/questions/39760871/socket-server-in-ios-nepackettunnelprovider-app-extension-cant-receive-connecti

**Comment by zhuhaow** [comment]
Well, I think you representation is a little misleading, because you are not dealing with IP packets with containing app.

The proxy server works fine, the problem is the SYN packet is never received by the TUN interface if I remember correctly, and that is what you should ask. You can check it by using tcpdump or wireshark. 

My guess is there is something special about how the system routing packets in this circumstance, maybe it's a bug.

**Comment by simpzan** [comment]
Yes, the modified packets sent to `packetFlow` not show up in tcpdump.
