### ISSUE TITLE
An error about tun2socks

### ISSUE THREAD

**Issue by 94haox** [zhuhaow/NEKit#187]
there will throw an error about tun2socks when run `carthage update --no-use-binaries --platform mac,ios`

check xcodebuild log:

error: could not read data from '/Users/duke/Pine/Carthage/Checkouts/tun2socks/tun2socks-iOS/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file.

** ARCHIVE FAILED **

The following build commands failed:
	ProcessInfoPlistFile /Users/duke/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/tun2socks/0.6.1/Build/Intermediates.noindex/ArchiveIntermediates/tun2socks-iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/tun2socks.framework/Info.plist tun2socks-iOS/Info.plist
(1 failure)

but I find info.plist in checkouts/tun2socks/tun2socks-ios.

emmmm, I don't understand with it😂, can you give me a solution？

**Comment by zhuhaow** [comment]
This sounds awkward. Have tried to remove the cache and Carthage folder and try again?

On 13 Aug 2018, at 17:43, DukeWu <notifications@github.com> wrote:

there will throw an error about tun2socks when run carthage update --no-use-binaries --platform mac,ios

check xcodebuild log:

error: could not read data from '/Users/duke/Pine/Carthage/Checkouts/tun2socks/tun2socks-iOS/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file.

** ARCHIVE FAILED **

The following build commands failed:
ProcessInfoPlistFile /Users/duke/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/tun2socks/0.6.1/Build/Intermediates.noindex/ArchiveIntermediates/tun2socks-iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/tun2socks.framework/Info.plist tun2socks-iOS/Info.plist
(1 failure)

but I find info.plist in checkouts/tun2socks/tun2socks-ios.

emmmm, I don't understand with it😂, can you give me a solution？

**Comment by 94haox** [comment]
yes, I tried.
I  removed Cartfile.resolved file and Carthage folder.

**Comment by zhuhaow** [comment]
Try also remove rm -rf ~/Library/Caches/org.carthage.CarthageKit

On 13 Aug 2018, at 17:58, DukeWu <notifications@github.com> wrote:

yes, I tried.
I removed Cartfile.resolved file and Carthage folder.

**Comment by 94haox** [comment]
Unfortunately, it  doesn't work 😂.

run `rm -rf ~/Library/Caches/org.carthage.CarthageKit`,
and remove Cartfile.resolved file and Carthage folder.
then run `carthage update --no-use-binaries --platform mac,ios`

still throw this error,  only me?

**Comment by 94haox** [comment]
Anyway，thanks😁

**Comment by 94haox** [comment]
Hey！ I found the reason of this error when I checked the xbuild error log.

error: could not read data from '/Carthage/Checkouts/tun2socks/tun2socks-iOS/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file.

Carthage needs read data from "tun2socks-iOS", but there was no "tun2socks-iOS", only "tun2socks-ios" 😂；

Then I renamed folder from "tun2socks-ios" to "tun2socks-iOS", and run again.

Then 🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by zhuhaow** [comment]
Though it looks like filesystem suppose to be case sensitive, but this is simply not the case for OS X, and you should reformat with case insensitive ASAP.

On 18 Aug 2018, at 11:07, DukeWu <notifications@github.com> wrote:

Closed #187.
