### ISSUE TITLE
How to create CNAME record?

### ISSUE THREAD

**Issue by ZonD80** [zhuhaow/NEKit#210]
Cname record creation is missing in DNSMessage.swift.
i've tried
var aswer = DNSResource(name: "test.local", type: .cname, klass: .internet, TTL: 10, data: "localhost".data(using: .utf8)!)

But it is not working. Can you help me?

**Comment by zhuhaow** [comment]
NEKit does not support it since there is no need for it inside NEKit. It is not design to be a general library for manipulating dns packets. Of course you can implement it and it should not be difficult.

On 5 Nov 2018, at 19:32, ZonD Eighty <notifications@github.com> wrote:

Cname record creation is missing in DNSMessage.swift.
i've tried
var aswer = DNSResource(name: "test.local", type: .cname, klass: .internet, TTL: 10, data: "localhost".data(using: .utf8)!)

But it is not working. Can you help me?
