### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by TheMrugraj** [zhuhaow/NEKit#226]
Is there any plan to have cocoapod support instead of Carthage. It would be great if someone helps in that because I am facing many issues due to `Carthage`.

**Comment by zhuhaow** [comment]
I’m happy to accept pull request.

在 2019年1月2日，17:44，Mrugrajsinh Vansadia <notifications@github.com> 写道：

Is there any plan to have cocoapod support instead of Carthage. It would be great if someone helps in that because I am facing many issues due to Carthage.

**Comment by TheMrugraj** [comment]
I am asking becauase After spending so much time in fixing smaller issues raised due to carthage my archive was rejected by iTunes connect. 

The reason is:

> Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

I am struggling lot in finding the solution to the above issue, but even after trying many workarounds suggested in carthage communities I am not able to upload archive successfully. Instead of exploring this beautiful library we have to waste efforts in Carthage related issues.

**Comment by zhuhaow** [comment]
Sorry to see that. But I’ve never published anything to AppStore so I couldn’t help.

It seems like you forgot to bundle some libraries in you host app. Note you may have to include libraries that you may not need but NEKit references to.

在 2019年1月2日，17:50，Mrugrajsinh Vansadia <notifications@github.com> 写道：

I am asking becauase After spending so much time in fixing smaller issues raised due to carthage my archive was rejected by iTunes connect.

The reason is:

Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

I am struggling lot in finding the solution to the above issue, but even after trying many workarounds suggested in carthage communities I am not able to upload archive successfully. Instead of exploring this beautiful library we have to waste efforts in Carthage related issues.

**Comment by twodayslate** [comment]
Ideally tun2socks and Resolver would also have to be converted to cocoapods
