### ISSUE TITLE
Mail app not working when connected through ss.

### ISSUE THREAD

**Issue by JayZhao** [zhuhaow/NEKit#69]
When ss is turned on, NEKit can establish a tcp connection but fail to read anything from the socket. It always return `NWTCPSocket got an error when reading data: Socket not connected`.

To reproduce, just use the system mail app to send an email. (Can be reproduced in both iOS & macOS)

Other ss client apps work just fine with the system mail app.

**Comment by itskeKs** [comment]
@jayzhao same here but it looks more like it is not working for microsoft exchange and only from time to time.

@zhuhaow for me it feels more like a https/ssl related issue. since exchange communicates through 443 (on my specific mal account) it works from time to time and i also ran into same error when i just browse the web. some https sites wont load properly.

**Comment by itskeKs** [comment]
@zhuhaow any ideas in this issue? :)

**Comment by zhuhaow** [comment]
Is this reproducible with other proxy apps?

**Comment by itskeKs** [comment]
no. potatso (not tested with potatso 2) has also a problem with the mail app but the problem there relies within DNS. on network change dns is not updated properly.
i will check with shadowrocket. need to figure out how to reproduce. it only happens with microsoft exchange since its getting mails through https.

**Comment by zhuhaow** [comment]
Many cloud service providers block the outgoing connection to SMTP servers.
So change the server provider or change the port of the SMTP server to something other than 25/465/587.
